swagger: '2.0'
info:
  version: 1.0.0
  title: Sensors
  x-ibm-name: sensors
  description: >-
    This API provides information about the recent readings of temperature
    sensors at the stores
host: $(catalog.host)
basePath: /api
paths:
  /sensors:
    get:
      responses:
        '200':
          description: 200 OK
securityDefinitions:
  clientID:
    description: ''
    in: header
    name: X-IBM-Client-Id
    type: apiKey
security:
  - clientID: []
x-ibm-configuration:
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)
          tls-profile: $(invoke-tls-profile)
  properties:
    runtime-url:
      value: ''
      description: ''
      encoded: false
    invoke-tls-profile:
      value: ''
      description: ''
      encoded: false
  catalogs:
    sb:
      properties:
        runtime-url: 'https://api-app-wow2016.mybluemix.net'
        invoke-tls-profile: 'client:Loopback-client'
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
